Repository kubesphere/s2ioperator, pull requests merged in 2019-12, with the labels that each got.

#124 clean s2ib s2ir s2ibt before exit s2ioperator
  Gopkg.lock
  test/e2e/e2e_suite_test.go
Labels: approved, size/S

#127 add s2ioperator lock
  Makefile
  test/Jenkinsfile.kubesphere
Labels: approved, size/S

#128 update the way to create the secret with CA cert and server cert/key
  .gitignore
  Makefile
  cmd/manager/main.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/default/webhookcainjection_patch.yaml
  config/kustomization.yaml
  config/manager/manager.yaml
  config/webhook/manifests.yaml
  deploy/s2ioperator.yaml
  go.mod
  hack/build-image.sh
  hack/certs.sh
  hack/e2etest.sh
  hack/update-cert.sh
  test/Jenkinsfile.kubesphere
Labels: approved, lgtm, size/L

#129 update readme dev-guide quick-start doc
  README.md
  docs/CRD-Consepts.md
  docs/DESIGN.md
  docs/DEVELOPMENT.md
  docs/QUICK-START.md
Labels: approved, lgtm, size/L

#130 update dev-guide link
  README.md
  docs/DEVELOPMENT.md
Labels: size/S

#131 update CRD-consepts doc
  docs/CRD-Consepts.md
  docs/s2i_arch.png
Labels: size/S
