Repository kubesphere/s2ioperator, pull requests merged in 2019-05, with the labels that each got.

#80 add s2ibt iconPath
  config/templates/java.yaml
  config/templates/nodejs.yaml
  config/templates/python.yaml
Labels: approved, lgtm, size/XS

#81 delete workload labels
  config/samples/autoscale/python-deployment.yaml
  config/samples/autoscale/python-statefulset.yaml
  pkg/controller/s2ibuilder/s2ibuilder_controller.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/M

#82 add failed init anno when s2ir failed
  CHANGELOG
  Makefile
  config/default/manager_image_patch.yaml
  config/samples/autoscale-failed/python-deployment.yaml
  config/samples/autoscale-failed/python-s2i-builder.yaml
  config/samples/autoscale-failed/python-s2i-run.yaml
  config/samples/autoscale-failed/python-statefulset.yaml
  deploy/s2ioperator.yaml
  pkg/controller/s2irun/s2irun_controller.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#83 Fixed Linked
  docs/builder_config.md
Labels: approved, lgtm, size/XS
