Repository kubesphere/s2ioperator, pull requests merged in 2019-09, with the labels that each got.

#100 fix order of format arugments
  pkg/controller/s2irun/ksbuilder_jobs.go
Labels: approved, lgtm, size/XS

#101 add s2i metrics to exporter
  Makefile
  cmd/manager/main.go
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_prometheus_metrics_patch.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/rbac_role.yaml
  deploy/s2ioperator.yaml
  pkg/controller/s2ibuilder/s2ibuilder_controller.go
  pkg/controller/s2irun/s2irun_controller.go
  pkg/metrics/metrics.go
Labels: approved, lgtm, size/L

#102 update label name
  pkg/controller/s2irun/ksbuilder_jobs.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/XS

#103 update default build source info
  pkg/controller/s2irun/s2irun_controller.go
Labels: approved, lgtm, size/M

#104 add mutatingwebhook
  pkg/webhook/default_server/add_validating.go
  pkg/webhook/default_server/s2ibuilder/mutating/create_update_webhook.go
  pkg/webhook/default_server/s2ibuilder/mutating/mutate.go
  pkg/webhook/default_server/s2ibuilder/mutating/s2ibuilder_create_update_handler.go
  pkg/webhook/default_server/s2ibuilder/mutating/webhooks.go
  pkg/webhook/default_server/s2irun/validating/s2irun_create_update_handler.go
Labels: approved, lgtm, size/L

#105 update label
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
  deploy/s2ioperator.yaml
  pkg/webhook/default_server/server.go
Labels: approved, lgtm, size/S

#106 update label for prometheus select
  config/rbac/auth_proxy_service.yaml
  deploy/s2ioperator.yaml
Labels: approved, lgtm, size/XS

#107 change tomcat codeFramework
  config/templates/tomcat.yaml
Labels: approved, size/XS
