Repository kubesphere/s2ioperator, pull requests merged in 2019-08, with the labels that each got.

#93 add binding volume
  config/crds/devops_v1alpha1_s2ibuildertemplate.yaml
  config/manager/manager.yaml
  config/samples/autoscale-failed/python-s2i-builder.yaml
  config/samples/devops_v1alpha1_s2ibuilder.yaml
  config/samples/devops_v1alpha2_s2ibuilder_runtimeimage.yaml
  config/templates/java.yaml
  config/templates/nodejs.yaml
  config/templates/python.yaml
  deploy/s2ioperator.yaml
  pkg/apis/devops/v1alpha1/openapi_generated.go
  pkg/apis/devops/v1alpha1/s2ibuildertemplate_types.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#95 update cache volume
  config/crds/devops_v1alpha1_s2ibuildertemplate.yaml
  config/samples/autoscale-failed/python-s2i-builder.yaml
  config/samples/devops_v1alpha1_s2ibuilder.yaml
  config/samples/devops_v1alpha2_s2ibuilder_runtimeimage.yaml
  config/templates/java.yaml
  config/templates/nodejs.yaml
  config/templates/python.yaml
  deploy/s2ioperator.yaml
  pkg/apis/devops/v1alpha1/openapi_generated.go
  pkg/apis/devops/v1alpha1/s2ibuildertemplate_types.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
Labels: approved, area/cache, lgtm, size/M

#94 add node affinity
  config/crds/devops_v1alpha1_s2ibuilder.yaml
  config/samples/devops_v1alpha1_s2ibuilder.yaml
  deploy/s2ioperator.yaml
  pkg/apis/devops/v1alpha1/openapi_generated.go
  pkg/apis/devops/v1alpha1/s2ibuilder_types.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/s2irun/ksbuilder_jobs.go
  pkg/controller/s2irun/s2irun_controller.go
  test/e2e/e2e_test.go
Labels: approved, area/cache, kind/feature, lgtm, size/L

#97 s2i binary template
  Makefile
  config/default/manager_image_patch.yaml
  config/templates/binary.yaml
  config/templates/java.yaml
  config/templates/tomcat.yaml
Labels: approved, lgtm, size/S

#98 b2i donot need sourceurl
  config/samples/b2i/tomcat-s2i-builder.yaml
  config/samples/b2i/tomcat-s2i-run.yaml
  pkg/webhook/default_server/s2ibuilder/validating/s2ibuilder_create_update_handler.go
  pkg/webhook/default_server/s2ibuilder/validating/validate.go
Labels: approved, lgtm, size/XS

#99 add output result
  config/crds/devops_v1alpha1_s2ibuilder.yaml
  config/crds/devops_v1alpha1_s2irun.yaml
  config/manager/manager.yaml
  config/rbac/rbac_role.yaml
  config/samples/devops_v1alpha1_s2ibuilder.yaml
  deploy/s2ioperator.yaml
  pkg/apis/devops/v1alpha1/openapi_generated.go
  pkg/apis/devops/v1alpha1/s2ibuilder_types.go
  pkg/apis/devops/v1alpha1/s2irun_types.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/s2irun/ksbuilder_jobs.go
  pkg/controller/s2irun/s2irun_controller.go
  test/e2e/e2e_test.go
Labels: approved, kind/feature, lgtm, size/XL
