Repository kubesphere/s2ioperator, pull requests merged in 2019-03, with the labels that each got.

#17 ✨Several improvements
  Makefile
  config/crds/devops_v1alpha1_s2ibuildertemplate.yaml
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  deploy/s2ioperator.yaml
  pkg/apis/devops/v1alpha1/s2ibuildertemplate_types.go
  pkg/apis/devops/v1alpha1/s2ibuildertemplate_types_test.go
  pkg/controller/s2irun/ksbuilder_jobs.go
  pkg/webhook/default_server/s2ibuilder/validating/s2ibuilder_create_update_handler.go
Labels: enhancement

#18 ✨add starttime in `kubectl get s2ir`
  config/crds/devops_v1alpha1_s2irun.yaml
  deploy/s2ioperator.yaml
  pkg/apis/devops/v1alpha1/s2irun_types.go
Labels: enhancement

#19 📖add s2ibuilder doc
  docs/builder_config.md
Labels: doc

#21 ✨Add LogURL of each s2irun
  .gitignore
  Makefile
  README.md
  config/crds/devops_v1alpha1_s2irun.yaml
  config/default/manager_image_patch.yaml-e
  config/rbac/rbac_role.yaml
  deploy/s2ioperator.yaml
  hack/build-image.sh
  hack/certs.sh
  hack/install_tools.sh
  pkg/apis/devops/v1alpha1/s2irun_types.go
  pkg/controller/s2irun/s2irun_controller.go
  pkg/handler/log/log.go
  pkg/handler/log/log_suite_test.go
Labels: enhancement

#24 s2i template
  config/crds/devops_v1alpha1_s2ibuilder.yaml
  config/crds/devops_v1alpha1_s2ibuildertemplate.yaml
  config/default/manager_image_patch.yaml-e
  config/templates/python.yaml
  pkg/apis/devops/v1alpha1/s2ibuilder_types.go
  pkg/apis/devops/v1alpha1/s2ibuildertemplate_types.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/s2irun/ksbuilder_jobs.go
  pkg/util/reflectutils/reflect.go
  pkg/util/reflectutils/reflect_test.go
  pkg/webhook/default_server/add_validating.go
  pkg/webhook/default_server/s2ibuilder/validating/s2ibuilder_create_update_handler.go
  pkg/webhook/default_server/s2ibuildertemplate/validating/create_update_webhook.go
  pkg/webhook/default_server/s2ibuildertemplate/validating/s2ibuildertemplate_create_update_handler.go
  pkg/webhook/default_server/s2ibuildertemplate/validating/validate.go
  pkg/webhook/default_server/s2ibuildertemplate/validating/webhooks.go
Labels: enhancement

#25 Add more integration tests
  .gitignore
  Makefile
  hack/install_tools.sh
  pkg/apis/devops/v1alpha1/s2ibuildertemplate_types.go
  pkg/controller/s2irun/ksbuilder_jobs.go
  pkg/controller/s2irun/s2irun_controller_test.go
  pkg/controller/s2irun/s2irun_suite_test.go
  pkg/webhook/default_server/s2ibuilder/validating/s2ibuilder_create_update_handler.go
  pkg/webhook/default_server/s2ibuilder/validating/validate.go
  pkg/webhook/default_server/s2ibuilder/validating/validating_suite_test.go
Labels: enhancement

#31 fix #26
  pkg/controller/s2ibuilder/s2ibuilder_controller.go
Labels: bug-fix

#33 Add jenkinsfile to test e2e
  Makefile
  test/Docker/Dockerfile
  test/Jenkinsfile
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
Labels: enhancement

#38 fix exit code
  hack/e2etest.sh
Labels: bug-fix

#39 add kubesphere's jenkinsfile
  test/Jenkinsfile.kubesphere
Labels: enhancement

#41 add owner
  OWNERS
Labels: size/XS

#42 add changelog
  CHANGELOG
Labels: approved, lgtm, size/XS

#45 Optimize reconcile logic and test case to avoid some errors
  Makefile
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  deploy/s2ioperator.yaml
  hack/e2etest.sh
  pkg/controller/s2irun/s2irun_controller.go
  test/e2e/e2e_test.go
Labels: approved, bug-fix, lgtm, size/L

#46 use s2irun uuid as job/cm name
  pkg/controller/s2irun/ksbuilder_jobs.go
  pkg/controller/s2irun/s2irun_controller.go
  pkg/controller/s2irun/s2irun_controller_test.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/M

#47 Add seed to container name to avoid concurrent-building fail
  Makefile
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  deploy/s2ioperator.yaml
  hack/e2etest.sh
  pkg/util/e2eutil/e2euitl.go
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm, size/M

#49 mv controller to kubesphere-devops-system
  .gitignore
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  deploy/s2ioperator.yaml
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm, size/M

#51 Release v0.0.2
  CHANGELOG
Labels: approved, lgtm, size/S

#52 update python template
  config/templates/python.yaml
Labels: approved, lgtm, size/M

#53 update readme
  Makefile
  README.md
  config/default/manager_image_patch.yaml
  deploy/s2ioperator.yaml
Labels: approved, doc, lgtm, size/S

#54 Update template
  config/templates/java.yaml
  config/templates/nodejs.yaml
  config/templates/python.yaml
Labels: approved, lgtm, size/L

#58 change log api version & change logger name
  pkg/controller/s2ibuilder/s2ibuilder_controller.go
  pkg/handler/log/log.go
  pkg/handler/log/log_suite_test.go
Labels: approved, lgtm, size/XS

#59 add docker secret support
  config/crds/devops_v1alpha1_s2ibuilder.yaml
  config/rbac/rbac_role.yaml
  config/samples/secret/devops_v1alpha1_s2ibuilder.yaml
  config/samples/secret/devops_v1alpha1_s2irun.yaml
  config/samples/secret/secret.yaml
  pkg/apis/devops/v1alpha1/s2ibuilder_types.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/s2irun/ksbuilder_jobs.go
  pkg/controller/s2irun/s2irun_controller.go
  pkg/webhook/default_server/s2ibuilder/validating/validate.go
Labels: approved, lgtm, size/L

#61 add secret support
  config/crds/devops_v1alpha1_s2ibuilder.yaml
  config/rbac/rbac_role.yaml
  config/samples/secret/devops_v1alpha1_s2ibuilder.yaml
  config/samples/secret/devops_v1alpha1_s2irun.yaml
  config/samples/secret/secret.yaml
  pkg/apis/devops/v1alpha1/s2ibuilder_types.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/s2irun/ksbuilder_jobs.go
  pkg/controller/s2irun/s2irun_controller.go
  pkg/webhook/default_server/s2ibuilder/validating/validate.go
  test/Jenkinsfile.kubesphere
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#62 add git secret support
  config/crds/devops_v1alpha1_s2ibuilder.yaml
  config/samples/git-secret/devops_v1alpha1_s2ibuilder.yaml
  config/samples/git-secret/devops_v1alpha1_s2irun.yaml
  config/samples/git-secret/secret.yaml
  pkg/apis/devops/v1alpha1/s2ibuilder_types.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/s2irun/ksbuilder_jobs.go
  test/Jenkinsfile.kubesphere
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#63 update deploy yaml
  CHANGELOG
  deploy/s2ioperator.yaml
Labels: approved, lgtm, size/M

#64 set log url when job start run
  pkg/controller/s2irun/s2irun_controller.go
Labels: approved, lgtm, size/S

#65 add image name status
  config/crds/devops_v1alpha1_s2irun.yaml
  deploy/s2ioperator.yaml
  pkg/apis/devops/v1alpha1/s2irun_types.go
  pkg/controller/s2irun/s2irun_controller.go
Labels: approved, lgtm, size/S

#66 validate update
  CHANGELOG
  pkg/webhook/default_server/add_validating.go
  pkg/webhook/default_server/s2ibuilder/validating/s2ibuilder_create_update_handler.go
  pkg/webhook/default_server/s2ibuildertemplate/validating/s2ibuildertemplate_create_update_handler.go
  pkg/webhook/default_server/s2irun/validating/create_update_webhook.go
  pkg/webhook/default_server/s2irun/validating/s2irun_create_update_handler.go
  pkg/webhook/default_server/s2irun/validating/validate.go
  pkg/webhook/default_server/s2irun/validating/webhooks.go
Labels: approved, lgtm, size/L

#67 add field json tag
  CHANGELOG
  config/crds/devops_v1alpha1_s2ibuilder.yaml
  deploy/s2ioperator.yaml
  pkg/apis/devops/v1alpha1/s2ibuilder_types.go
Labels: approved, lgtm, size/M

#68 add label annotations
  pkg/apis/devops/v1alpha1/s2ibuilder_types.go
  pkg/controller/s2irun/ksbuilder_jobs.go
  pkg/controller/s2irun/s2irun_controller.go
Labels: approved, lgtm, size/M
