Repository kubesphere/s2ioperator, pull requests merged in 2019-10, with the labels that each got.

#108 fix imagePullPolicy
  deploy/s2ioperator.yaml
  pkg/webhook/default_server/s2ibuilder/mutating/create_update_webhook.go
  pkg/webhook/default_server/s2ibuilder/mutating/s2ibuilder_create_update_handler.go
  test/Jenkinsfile.kubesphere
Labels: approved, lgtm, size/S

#109 Fix/jenkinsfile
  test/Jenkinsfile.kubesphere
Labels: approved, lgtm, size/S

#110 do no retry scale workload, if workload is not found
  pkg/controller/s2irun/s2irun_controller.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/XS

#111 add s2itemaplte anno
  config/templates/binary.yaml
  config/templates/java.yaml
  config/templates/nodejs.yaml
  config/templates/python.yaml
  config/templates/tomcat.yaml
Labels: approved, size/S

#113 translate s2ibt description.
  config/templates/binary.yaml
  config/templates/java.yaml
  config/templates/nodejs.yaml
  config/templates/python.yaml
  config/templates/tomcat.yaml
Labels: approved, lgtm, size/S

#114 fix typo
  config/templates/nodejs.yaml
  config/templates/python.yaml
  config/templates/tomcat.yaml
Labels: approved, lgtm, size/XS

#115 update java templates description
  config/templates/java.yaml
Labels: approved, lgtm, size/XS

#116 update template description
  config/templates/binary.yaml
  config/templates/java.yaml
  config/templates/nodejs.yaml
  config/templates/python.yaml
  config/templates/tomcat.yaml
Labels: approved, lgtm, size/S
