Repository kubesphere/s2ioperator, pull requests merged in 2020-11, with the labels that each got.

#142 Unify the format of DEVELOPMENT.md
  docs/DEVELOPMENT.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, needs-ok-to-test, size/S

#141 Fix a broken link of contribution guide
  README.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#143 improvement: remove some approvers
  OWNERS
Labels: approved, dco-signoff: no, size/XS

#144 minor
  .gitignore
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#145 minor
  README.md
Labels: approved, dco-signoff: yes, size/XS

#147 fix webhook trigger
  Makefile
  OWNERS
  config/crds/devops.kubesphere.io_s2ibuildertemplates.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_webhook_trigger.yaml
  config/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  deploy/s2ioperator.yaml
  github.com/kubesphere/s2ioperator/pkg/apis/devops/v1alpha1/openapi_generated.go
  pkg/apis/devops/v1alpha1/s2ibuilder_webhook.go
Labels: approved, dco-signoff: no, do-not-merge/invalid-owners-file, size/XXL
